### ISSUE TITLE
How to set mysql and make it work with docker-image-pier?

### ISSUE THREAD

**Issue by SydOps** [zhengxiaochuan-3/docker-image-pier#1]
Hi xiaochuan,

How to set mysql and make it work with docker-image-pier?

When try to push the image to docker-image-pier, I got `500` error.

```
$ git clone https://github.com/zhengxiaochuan-3/docker-image-pier.git
$ cd docker-image-pier
$ docker build -t docker-image-pier . 
$ docker tag f4fddc471ec2 192.168.99.100:5000/alpine
$ docker push 192.168.99.100:5000/alpine
The push refers to a repository [192.168.99.100:5000/alpine] (len: 1)
Sending image list
Pushing repository 192.168.99.100:5000/alpine (1 tags)
Image f4fddc471ec2 already pushed, skipping
Pushing tag for rev [f4fddc471ec2] on {http://192.168.99.100:5000/v1/repositories/alpine/tags/latest}
Internal server error: 500 trying to push tag latest on alpine
```

### Check logs, seems it relates with mysql. But I have tried to link it with below command (no worry about the storage setting for mysql)

    $ docker run --name mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:5.6
    $ docker run --name pier --link mysql:mysql -d -p 5000:5000 docker-image-pier

Docker container's log for reference:
```
08/Nov/2015:12:27:04 +0000 DEBUG: args = {'namespace': 'library', 'repository': u'alpine'}
08/Nov/2015:12:27:04 +0000 DEBUG: DB _handle_repository_created ...
192.168.99.100 - - [08/Nov/2015:12:27:04 +0000] "GET /v2/ HTTP/1.1" 404 233 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64"
08/Nov/2015:12:27:04 +0000 DEBUG: args = {'image_id': u'f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0'}
08/Nov/2015:12:27:04 +0000 DEBUG: api_error: Image not found
192.168.99.100 - - [08/Nov/2015:12:27:04 +0000] "GET /v1/images/f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0/json HTTP/1.1" 404 28 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64"
08/Nov/2015:12:27:04 +0000 DEBUG: args = {'image_id': u'f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0'}
08/Nov/2015:12:27:04 +0000 DEBUG: put_image_json: json_data:{"id":"f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0","created":"2015-09-14T20:01:14.810993981Z","container":"afbbf75ae75dd44fbb1d3376e011bfef2747745a70570d5e88aabaebd42997a1","container_config":{"Hostname":"afbbf75ae75d","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":null,"PublishService":"","Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":["/bin/sh","-c","#(nop) ADD file:43a95cc218d164ff589cb91519964373d53b607469f5ccce725631916392cd88 in /"],"Image":"","Volumes":null,"VolumeDriver":"","WorkingDir":"","Entrypoint":null,"NetworkDisabled":false,"MacAddress":"","OnBuild":null,"Labels":null},"docker_version":"1.8.2","config":{"Hostname":"afbbf75ae75d","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":null,"PublishService":"","Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Image":"","Volumes":null,"VolumeDriver":"","WorkingDir":"","Entrypoint":null,"NetworkDisabled":false,"MacAddress":"","OnBuild":null,"Labels":null},"architecture":"amd64","os":"linux","Size":5248903}

192.168.99.100 - - [08/Nov/2015:12:27:04 +0000] "PUT /v1/images/f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0/json HTTP/1.1" 200 4 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64"
192.168.99.100 - - [08/Nov/2015:12:27:04 +0000] "PUT /v1/repositories/alpine/ HTTP/1.1" 200 2 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64"
08/Nov/2015:12:27:04 +0000 DEBUG: args = {'image_id': u'f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0'}
08/Nov/2015:12:27:04 +0000 DEBUG: put_image_layer: json_data:{"id":"f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0","created":"2015-09-14T20:01:14.810993981Z","container":"afbbf75ae75dd44fbb1d3376e011bfef2747745a70570d5e88aabaebd42997a1","container_config":{"Hostname":"afbbf75ae75d","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":null,"PublishService":"","Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":["/bin/sh","-c","#(nop) ADD file:43a95cc218d164ff589cb91519964373d53b607469f5ccce725631916392cd88 in /"],"Image":"","Volumes":null,"VolumeDriver":"","WorkingDir":"","Entrypoint":null,"NetworkDisabled":false,"MacAddress":"","OnBuild":null,"Labels":null},"docker_version":"1.8.2","config":{"Hostname":"afbbf75ae75d","Domainname":"","User":"","AttachStdin":false,"AttachStdout":false,"AttachStderr":false,"ExposedPorts":null,"PublishService":"","Tty":false,"OpenStdin":false,"StdinOnce":false,"Env":null,"Cmd":null,"Image":"","Volumes":null,"VolumeDriver":"","WorkingDir":"","Entrypoint":null,"NetworkDisabled":false,"MacAddress":"","OnBuild":null,"Labels":null},"architecture":"amd64","os":"linux","Size":5248903}

08/Nov/2015:12:27:04 +0000 DEBUG: simple_checksum_handler: return <sha256 HASH object @ 0x7f01d1eb69e0>
08/Nov/2015:12:27:05 +0000 DEBUG: [save_checksums]:checksumjson=["sha256:291ae321072c7728cd96bf90e0690477d2ec26540c3b6b2fcc7cbec3d2cd1e2c"]
192.168.99.100 - - [08/Nov/2015:12:27:05 +0000] "PUT /v1/images/f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0/layer HTTP/1.1" 200 4 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64"
08/Nov/2015:12:27:05 +0000 DEBUG: args = {'image_id': u'f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0'}
192.168.99.100 - - [08/Nov/2015:12:27:05 +0000] "PUT /v1/images/f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0/checksum HTTP/1.1" 200 4 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64"
08/Nov/2015:12:27:05 +0000 DEBUG: args = {'tag': u'3.2', 'namespace': 'library', 'repository': u'alpine'}
08/Nov/2015:12:27:05 +0000 DEBUG: [put_tag] namespace=library; repository=alpine; tag=3.2
08/Nov/2015:12:27:05 +0000 DEBUG: put_tag data body is f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0
08/Nov/2015:12:27:05 +0000 DEBUG: [put_tag] increase layerID is f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0
08/Nov/2015:12:27:05 +0000 DEBUG: DB _handle_layer_increased ...
08/Nov/2015:12:27:05 +0000 WARNING: DB is disconnected. Reconnect to it.
08/Nov/2015:12:27:05 +0000 DEBUG: DB _handle_layer_increased ...
08/Nov/2015:12:27:05 +0000 WARNING: DB is disconnected. Reconnect to it.
08/Nov/2015:12:27:05 +0000 DEBUG: DB _handle_layer_increased ...
2015-11-08 12:27:05,640 ERROR: Exception on /v1/repositories/alpine/tags/3.2 [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 277, in wrapper
    return f(namespace=namespace, repository=repository, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 251, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/tags.py", line 242, in put_tag
    signals.layer_increased.send(sender, layer=layerID)
  File "/usr/local/lib/python2.7/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/db.py", line 62, in _retry
    raise e
OperationalError: (sqlite3.OperationalError) near "ON": syntax error [SQL: u"INSERT INTO layer (name,cnt) VALUES ('f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0',1) ON DUPLICATE KEY UPDATE cnt=cnt+1;"]
08/Nov/2015:12:27:05 +0000 ERROR: Exception on /v1/repositories/alpine/tags/3.2 [PUT]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 277, in wrapper
    return f(namespace=namespace, repository=repository, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/toolkit.py", line 251, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/tags.py", line 242, in put_tag
    signals.layer_increased.send(sender, layer=layerID)
  File "/usr/local/lib/python2.7/dist-packages/blinker/base.py", line 267, in send
    for receiver in self.receivers_for(sender)]
  File "/usr/local/lib/python2.7/dist-packages/docker_registry/lib/index/db.py", line 62, in _retry
    raise e
OperationalError: (sqlite3.OperationalError) near "ON": syntax error [SQL: u"INSERT INTO layer (name,cnt) VALUES ('f4fddc471ec22fc1f7d37768132f1753bc171121e30ac2af7fcb0302588197c0',1) ON DUPLICATE KEY UPDATE cnt=cnt+1;"]
192.168.99.100 - - [08/Nov/2015:12:27:05 +0000] "PUT /v1/repositories/alpine/tags/3.2 HTTP/1.1" 500 291 "-" "docker/1.8.2 go/go1.4.2 git-commit/0a8c2e3 kernel/4.0.9-boot2docker os/linux arch/amd64"
```

**Comment by zhengxiaochuan-3** [comment]
sorry for delay
you should configue 
sqlalchemy_index_database: mysql://root@mysqlhost:3306/registry 
in config.yml

**Comment by zhengxiaochuan-3** [comment]
@SydOps  did you try this ? how it works?

----------------------------
you should configue 
sqlalchemy_index_database: mysql://root@mysqlhost:3306/registry 
in config.yml

**Comment by SydOps** [comment]
I am still working on it, and not get it run properly. I knew you are busy for 11/11, will update you later.

**Comment by SydOps** [comment]
I still can't make it work. 

@zhengxiaochuan-3 

Could you please provide instructions I can follow up?

**Comment by zhengxiaochuan-3** [comment]
a sample instruction :

after docker-image-pier installed 

1.install mysql 
  yum install -y mysql-server mysql mysql-deve

2.make sure a user has all authorities ,and make sure you can login mysql by cmd in shell.

   GRANT ALL PRIVILEGES ON *.* TO 'jip'@'%' IDENTIFIED BY 'jip' WITH GRANT OPTION;
   FLUSH PRIVILEGES;
   commit;

3.create a database for example "registry",make sure you can use this database in mysql

4.configue  /etc/docker-registry/config.yml
    ##sqlalchemy_index_database: sqlite:////export/docker-registry/docker-registry.db
    sqlalchemy_index_database: mysql://root@mysqlhost:3306/registry 

5.service docker-registry restart

6.try again

if you make it work,let me kown.

**Comment by zhengxiaochuan-3** [comment]
@SydOps

**Comment by SydOps** [comment]
Thanks a lot, @zhengxiaochuan-3 

Let me try.

**Comment by zhengxiaochuan-3** [comment]
@SydOps 
Hi, a better instruction :
http://dockone.io/article/866

**Comment by SydOps** [comment]
After read the latest instruction, I can run docker registry in mysql.
